config/routes.rb
Rails.application.routes.draw do
  get 'demo' => redirect("http://demo.staytus.co", :status => 302)
  get 'repo' => redirect('http://github.com/adamcooke/staytus', :status => 302)
  get 'bug' => redirect('https://github.com/adamcooke/staytus/issues/new?labels=bug', :status => 302)
  get 'api' => redirect('https://github.com/adamcooke/staytus/tree/master/doc/api', :status => 302)
  get 'blog' => redirect('http://blog.staytus.co', :status => 302)
  get 'donate' => redirect("/", :status => 302)

  get 'install' => 'pages#install'
  root 'pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/github_controller.rb
class GithubController < ApplicationController

  before_filter do
    unless session[:github_token]
      redirect_to "/auth/github"
    end
  end

  def star
    if res = client.star("adamcooke/staytus")
      render :text => "Starred!"
    else
      render :text => "Not starred!"
    end
  end

  private

  def client
    client = Octokit::Client.new(:access_token => session[:github_token])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def github
    session[:github_token] = request.env['omniauth.auth'].credentials.token
    session[:github_uid] = request.env['omniauth.auth'].uid
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title #{@page_title} - Staytus
    = javascript_include_tag 'application'
    = stylesheet_link_tag 'application'
    = csrf_meta_tags
    %link{:href => image_path('favicon.png'), :rel => 'shortcut icon', :type => 'image/png'}
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,900' rel='stylesheet' type='text/css'>
    <meta content='width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1' name='viewport' />
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-44845543-2', 'auto');
      ga('send', 'pageview');
  %body{:class => Rails.env}
    = display_flash
    = yield

    .partnersBar
      .pageContainer
        %p.partnersBar__title
          Staytus would not be possible without the support from our partners below. Check them out.
        %ul.partnersBar__logos
          %li.partnersBar__logo= link_to image_tag('partners/viaduct.svg', :title => "Viaduct"), "http://viaduct.io"
          %li.partnersBar__logo= link_to image_tag('partners/atech.svg', :title => "aTech Media"), "http://atechmedia.com"
          %li.partnersBar__logo= link_to image_tag('partners/codebase.svg', :title => "Codebase"), "http://www.codebasehq.com"
          %li.partnersBar__logo= link_to image_tag('partners/deploy.svg', :title => "Deploy"), "http://www.deployhq.com"
    .siteFooter
      .pageContainer
        .siteFooter__navArea
          .siteFooter__primaryNav
            %p.siteFooter__header The Staytus Project
            %ul.siteFooter__nav
              %li= link_to "Homepage", root_path
              %li= link_to "Try the demo", 'http://demo.staytus.co'
              %li= link_to "Browse the code", 'https://github.com/adamcooke/staytus'
              %li= link_to "Submit a bug", 'https://github.com/adamcooke/staytus/issues/new?labels=bug'
              %li= link_to "API Docs", 'https://github.com/adamcooke/staytus/tree/stable/doc/api'
          .siteFooter__secondaryNav
            %p.siteFooter__header Keep in touch
            %ul.siteFooter__nav
              %li= link_to "Read our blog", 'http://blog.staytus.co'
              %li= link_to "Follow me on Twitter", "http://twitter.com/adamcooke"
              %li= link_to "Want to help out?", "mailto:me+staytus@adamcooke.io"

        .siteFooter__copyright
          %p.siteFooter__copyrightText Website copyright &copy; #{Date.today.year} Adam Cooke.
          %p
            This website is #{link_to 'open source', 'http://github.com/adamcooke/staytus-website'}. If you spot any issues, please feel free to submit a pull request on GitHub.

app/views/pages/home.html.haml
- @page_title = 'The Open Source Status Site'
.heroHeader{:class => "heroHeader--style0"}
  .heroHeader__logo= image_tag 'logo-white.svg', :class => ''
  .heroHeader__text
    .pageContainer
      %h1.heroHeader__title Your ultimate status site
      %p.heroHeader__intro Staytus is a free, open source & beautiful status site that you can install on your own servers. It’s fully-loaded with all the features you'd expect from any site you might pay for.
      %ul.heroHeader__buttons
        %li= link_to "Try the live demo", 'http://demo.staytus.co', :class => 'heroHeader__buttonTry'
        %li
          = link_to "Check out the code", 'https://github.com/adamcooke/staytus'
          .heroHeader__githubStar
      %p.heroHeader__install
        Want to use Staytus? #{link_to "Read about how to get started", install_path}

.featuresPage
  .pageContainer
    %h2.featurePage__heading So, what's all the fuss about?
    %p.featurePage__intro
      We're packing all the great features which you've come to expect
      from a hosted status page. Here's just a few of the things you
      can expect from Staytus.


    %ul.featuresPage__list
      %li.featuresPage__feature
        = image_tag 'icons/ui.svg', :class => 'featuresPage__icon'
        %h3.featuresPage__featureHeading Beautiful & responsive Interface
        %p.featuresPage__featureText
          Staytus has a default theme which is both sexy and responsive.
          It works well on desktop, tablet and mobile. You can always design your own themes, if you'd prefer.
      %li.featuresPage__feature
        = image_tag 'icons/issues.svg', :class => 'featuresPage__icon'
        %h3.featuresPage__featureHeading Track issues as they happen
        %p.featuresPage__featureText
          Your status site can keep track of issues as they happen. Just
          login to the admin UI and add issues and continuously post
          updates as the issue progresses.

    %ul.featuresPage__list
      %li.featuresPage__feature
        = image_tag 'icons/maintenance.svg', :class => 'featuresPage__icon'
        %h3.featuresPage__featureHeading Publish your maintenance sessions
        %p.featuresPage__featureText
          Every app/network needs some scheduled maintenance. Add your maintenance
          sessions and they'll be announced on your status site. Once in progress
          you can then provide updates as and when needed.

      %li.featuresPage__feature
        = image_tag 'icons/email.svg', :class => 'featuresPage__icon'
        %h3.featuresPage__featureHeading Allow visitors to subscribe by e-mail
        %p.featuresPage__featureText
          When issues happen, it's a good idea to let customer's know as quickly
          as possible. With Staytus, visitors can enter their e-mail address
          and we'll automatically notify them when you add new issues or maintenance sessions.

    %ul.featuresPage__list
      %li.featuresPage__feature
        = image_tag 'icons/api.svg', :class => 'featuresPage__icon'
        %h3.featuresPage__featureHeading Update from your external apps
        %p.featuresPage__featureText
          Staytus includes a JSON API which allows you to update statuses from
          external applications & sources. If you've got your own monitoring
          system, you can hook it up to update your status site.

      %li.featuresPage__feature
        = image_tag 'icons/users.svg', :class => 'featuresPage__icon'
        %h3.featuresPage__featureHeading Share your site with your colleagues
        %p.featuresPage__featureText
          As status site is only as good as the data you put in. Empower your
          whole team to add new updates when issues arise to ensure customers
          are always informed.

app/views/pages/install.html.haml
- @page_title = "How do I install Staytus?"
.installPage
  .pageContainer
    = link_to "Back to homepage", root_path, :class => 'installPage__back'
    %h1.installPage__heading How do I install Staytus?
    %p.installPage__intro
      Here are some instructions on how you can easily get Staytus installed
      and running for you.

  .installPage__section.installPage__section--viaduct
    .pageContainer
      .installPage__sectionLeft
        %h2.installPage__sectionHeading Use the Viaduct app hosting platform
        %p.installPage__sectionText
          The easiest and quickest way to deploy Staytus is to use the
          #{link_to "Viaduct", "http://viaduct.io"} application hosting platform.
      .installPage__sectionRight
        %ol.installPage__sectionInstructions
          %li= link_to "Sign up for a Viaduct account", "http://my.viaduct.io"
          %li Select <b>Use the App Store</b> from your dashboard
          %li Choose <b>Staytus</b> from the <b>CMS</b> category.
          %li Follow the instructions and Staytus will be deployed straight away.
          %li Once installed you can add your own custom domains and SSL, if needed using the Viaduct interface.
        %p.installPage__upgrade
          If you want to upgrade once you've deployed to Viaduct, you can simply
          hit the <b>Deploy Now</b> button and the latest version will be
          deployed for you and your data will be migrated.

  .installPage__section
    .pageContainer
      .installPage__sectionLeft
        %h2.installPage__sectionHeading Install Staytus on your own server
        %p.installPage__sectionText
          If you know your way around a server, you can install Staytus yourself
          on your own Linux server. Just follow these instructions to install
          Staytus.
        %p.installPage__sectionText
          Further information about installing Staytus can be found in the
          #{link_to 'README', 'https://github.com/adamcooke/staytus/tree/stable/README.md'}
          file in the repository.

      .installPage__sectionRight
        %ol.installPage__sectionInstructions
          %li
            Ensure your server has all the required prerequisites installed.
            Specifically Ruby 2.0 or higher (plus RubyGems), MySQL
            Server &amp; Git.
          %li
            Create a database and user on your MySQL server.
          %li
            Clone the Staytus repostiory using Git and then checkout the stable
            branch which contains the most recent stable version of Staytus.
            %pre.installPage__code
              git clone https://github.com/adamcooke/staytus /opt/staytus<br>
              cd /opt/staytus<br>
              git checkout stable
          %li
            Install all the required Ruby dependencies.
            %pre.installPage__code
              gem install bundler <span># If you don't already have it</span><br>
              bundle install --deployment --without development:test

          %li
            Copy your database configuration file into place and add your database
            connection details.
            %pre.installPage__code
              cp config/database.example.yml config/database.yml <br>
              nano -w config/database.yml

          %li
            Run the Staytus installation script which will populate the database
            schema and compile assets.
            %pre.installPage__code
              bundle exec rake staytus:build staytus:install

          %li
            Start the Staytus application. This will run Staytus in the foreground.
            You can use whatever tools you wish to run this in the background.
            %pre.installPage__code
              bundle exec foreman start

          %li
            When you want to upgrade, you can just pull the latest version of the
            code, run the upgrade script and restart the app.
            %pre.installPage__code
              git pull origin stable<br>
              bundle<br>
              bundle exec rake staytus:build staytus:upgrade<br>
              bundle exec foreman start